language: csharp
solution: ./website.sln
dist: trusty 
install: dotnet restore
script:
    dotnet build /home/travis/build/GBSal/ConfigTravis/Website/Website.csproj -c release
matrix:
  include:
    - dotnet: 1.0.1
      mono: none


      
     