language: csharp
solution:  website/website.sln
dist: trusty 
install: dotnet restore ./website/website.sln
script:
    dotnet build ./website/website.sln -c release
matrix:
  include:
    - dotnet: 1.0.1
      mono: none


      
     
