language: csharp
solution: ./website.sln
dist: trusty 
#sudo: required
install: dotnet restore
script:
    dotnet build .\Website.sln -c release
matrix:
  include:
    - dotnet: 1.0.1
      mono: none


      
     